apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
  monitorAccounts: {{ .Values.secret.monitorAccounts | b64enc | quote }}
  serviceAccountJson: {{ .Values.secret.serviceAccountJson | b64enc | quote }}
