replicaCount: 1

image:
  repository: web3f/polkadot-account-monitoring
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: v0.1.6

config:
  log_level: debug
  accounts_file: accounts/accounts.yml
  database:
    uri: "mongodb://username:password123@mongodb-0.mongodb-headless:27017,mongodb-1.mongodb-headless:27017/monitor"
    name: "monitor"
  # (optional): types of extrinsics to fetch from chain.
  collection:
    modules:
      - transfer
      - rewards_slashes
      - nominations
  # (optional): types of reports to generate
  # report:
  #   modules:
  #     - transfers
  #   publisher:
  #     type: google_drive
  #     config:
  #       bucket_name: report-bucket
  #       credentials: credentials/credentials.json
  cronjob:
    enabled: false
    schedule: "* * * * *"

secret:
  monitorAccounts:
    - stash: 1a2YiGNu1UUhJtihq8961c7FZtWGQuWDVMWTNBKJdmpGhZP
      network: polkadot
      description: Alice's account
    - stash: 1b3NhsSEqWSQwS6nPGKgCrSjv9Kp13CnhraLV5Coyd8ooXB
      network: polkadot
      description: Bob's account
    - stash: 1cNyFSmLW4ofr7xh38za6JxLFxcu548LPcfc1E6L9r57SE3
      network: polkadot
      description: Eve's account
  serviceAccountJson: |
    {"type":"service_account","project_id":"xxx","private_key_id":"xxx","private_key":"xxx"}
