{{ if eq .Values.config.cronjob.enabled true }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  schedule: {{ .Values.config.cronjob.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1200
      template:
        metadata:
          labels:
            app: {{ .Release.Name }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              volumeMounts:
              - name: config
                mountPath: /app/config
              - name: credentials
                mountPath: /app/credentials
                readOnly: true 
              - name: accounts
                mountPath: /app/accounts      
          volumes:
          - name: config
            configMap:
              name: {{ .Release.Name }}-config
          - name: credentials
            secret:
              secretName: {{ .Release.Name }}
              items:
                - key: serviceAccountJson
                  path: credentials.json
          - name: accounts
            configMap:
              name: {{ .Release.Name }}-accounts  
{{ end }}
