{{ if ne .Values.config.cronjob.enabled true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: config
            mountPath: /app/config
          - name: accounts
            mountPath: /app/accounts   
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-config
      - name: accounts
        configMap:
          name: {{ .Release.Name }}-accounts  
{{ end }}
