log_level: debug
accounts_file: config/sample.accounts.yml
database:
  uri: "mongodb://localhost:27017/"
  name: "monitor"
# (optional): types of extrinsics to fetch from chain.
collection:
  modules:
    - transfer
    - rewards_slashes
    - nominations
# (optional): types of reports to generate
report:
  modules:
    - transfers
  publisher:
    type: google_drive
    config:
      bucket_name: report-bucket
      credentials: config/credentials.json
