- stash: 1a2YiGNu1UUhJtihq8961c7FZtWGQuWDVMWTNBKJdmpGhZP
  network: polkadot
  description: Alice's account
- stash: 1b3NhsSEqWSQwS6nPGKgCrSjv9Kp13CnhraLV5Coyd8ooXB
  network: polkadot
  description: Bob's account
- stash: 1cNyFSmLW4ofr7xh38za6JxLFxcu548LPcfc1E6L9r57SE3
  network: polkadot
  description: Eve's account
