environments:
  ci:
  local:  

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/

releases:
- name: polkadot-account-monitor
  chart: ../charts/polkadot-account-monitoring
  values:
  - ./config/monitor.yaml.gotmpl

